/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#121411",
        surface: "#121411",
        "surface-dim": "#121411",
        "surface-bright": "#383a36",
        "surface-container-lowest": "#0d0f0c",
        "surface-container-low": "#1a1c19",
        "surface-container": "#1e201d",
        "surface-container-high": "#292a27",
        "surface-container-highest": "#333532",
        "surface-variant": "#333532",
        "on-surface": "#e3e3de",
        "on-surface-variant": "#ddc1b3",
        "inverse-surface": "#e3e3de",
        "inverse-on-surface": "#2f312e",
        outline: "#a58c7f",
        "outline-variant": "#564338",
        "surface-tint": "#ffb68d",
        primary: "#ffb68d",
        "primary-container": "#df7328",
        "on-primary": "#532200",
        "on-primary-container": "#481d00",
        "inverse-primary": "#9a4600",
        "primary-fixed": "#ffdbc9",
        "primary-fixed-dim": "#ffb68d",
        "on-primary-fixed": "#321200",
        "on-primary-fixed-variant": "#763400",
        secondary: "#ffb77b",
        "secondary-container": "#7a4100",
        "on-secondary": "#4d2700",
        "on-secondary-container": "#ffb270",
        "secondary-fixed": "#ffdcc2",
        "secondary-fixed-dim": "#ffb77b",
        "on-secondary-fixed": "#2e1500",
        "on-secondary-fixed-variant": "#6d3a00",
        tertiary: "#c9c6c5",
        "tertiary-container": "#929090",
        "on-tertiary": "#313030",
        "on-tertiary-container": "#2a2a29",
        "tertiary-fixed": "#e5e2e1",
        "tertiary-fixed-dim": "#c9c6c5",
        "on-tertiary-fixed": "#1c1b1b",
        "on-tertiary-fixed-variant": "#474646",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "mono-data": ["Geist", "monospace"],
        "editorial-italic": ["EB Garamond", "serif"],
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "container-max": "1440px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      keyframes: {
        ticker: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.4", transform: "scale(1)" },
          "50%": { opacity: "0.7", transform: "scale(1.05)" },
        },
      },
      animation: {
        ticker: "ticker 25s linear infinite",
        "pulse-glow": "pulse-glow 4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
}
