from abc import ABC, abstractmethod
from typing import List, Optional, Dict, Any
from backend.app.models.domain import (
    User, Workspace, WorkspaceMember, UserSession, EmailVerification, PasswordResetToken, LoginEvent,
    Product, Category, PlatformMetrics, Alert, Notification, Report, DataSource, UserSettings,
    SubscriptionPlan, UserSubscription, CreditAccount, CreditTransaction, CreditUsage
)

class UserRepository(ABC):
    @abstractmethod
    def get_by_id(self, user_id: str) -> Optional[User]: ...
    @abstractmethod
    def get_by_email(self, email: str) -> Optional[User]: ...
    @abstractmethod
    def get_by_verification_token(self, token: str) -> Optional[User]: ...
    @abstractmethod
    def get_by_reset_token(self, token: str) -> Optional[User]: ...
    @abstractmethod
    def create(self, user: User) -> User: ...
    @abstractmethod
    def update(self, user: User) -> User: ...
    @abstractmethod
    def delete(self, user_id: str) -> bool: ...

class WorkspaceRepository(ABC):
    @abstractmethod
    def get_by_id(self, workspace_id: str) -> Optional[Workspace]: ...
    @abstractmethod
    def get_by_owner_id(self, owner_id: str) -> Optional[Workspace]: ...
    @abstractmethod
    def create(self, workspace: Workspace) -> Workspace: ...
    @abstractmethod
    def update(self, workspace: Workspace) -> Workspace: ...
    @abstractmethod
    def add_member(self, member: WorkspaceMember) -> WorkspaceMember: ...
    @abstractmethod
    def get_members(self, workspace_id: str) -> List[WorkspaceMember]: ...
    @abstractmethod
    def delete(self, workspace_id: str) -> bool: ...

class AuthPersistenceRepository(ABC):
    @abstractmethod
    def create_session(self, session: UserSession) -> UserSession: ...
    @abstractmethod
    def get_session(self, token_hash: str) -> Optional[UserSession]: ...
    @abstractmethod
    def revoke_session(self, token_hash: str) -> bool: ...
    @abstractmethod
    def revoke_all_user_sessions(self, user_id: str) -> int: ...
    @abstractmethod
    def create_email_verification(self, verification: EmailVerification) -> EmailVerification: ...
    @abstractmethod
    def get_email_verification(self, token: str) -> Optional[EmailVerification]: ...
    @abstractmethod
    def mark_email_verification_used(self, token: str) -> bool: ...
    @abstractmethod
    def create_password_reset_token(self, reset_token: PasswordResetToken) -> PasswordResetToken: ...
    @abstractmethod
    def get_password_reset_token(self, token: str) -> Optional[PasswordResetToken]: ...
    @abstractmethod
    def mark_password_reset_token_used(self, token: str) -> bool: ...
    @abstractmethod
    def record_login_event(self, event: LoginEvent) -> LoginEvent: ...
    @abstractmethod
    def list_login_events(self, user_id: Optional[str] = None, email: Optional[str] = None) -> List[LoginEvent]: ...

class SubscriptionRepository(ABC):
    @abstractmethod
    def list_plans(self, active_only: bool = True) -> List[SubscriptionPlan]: ...
    @abstractmethod
    def get_plan_by_id(self, plan_id: str) -> Optional[SubscriptionPlan]: ...
    @abstractmethod
    def get_plan_by_slug(self, slug: str) -> Optional[SubscriptionPlan]: ...
    @abstractmethod
    def get_user_subscription(self, user_id: str) -> Optional[UserSubscription]: ...
    @abstractmethod
    def create_user_subscription(self, subscription: UserSubscription) -> UserSubscription: ...
    @abstractmethod
    def update_user_subscription(self, subscription: UserSubscription) -> UserSubscription: ...

class CreditRepository(ABC):
    @abstractmethod
    def get_or_create_account(self, user_id: str) -> CreditAccount: ...
    @abstractmethod
    def get_account(self, user_id: str) -> Optional[CreditAccount]: ...
    @abstractmethod
    def update_account_balance(self, user_id: str, new_balance: int, delta_granted: int, delta_used: int) -> CreditAccount: ...
    @abstractmethod
    def create_transaction(self, tx: CreditTransaction) -> CreditTransaction: ...
    @abstractmethod
    def get_transaction_by_reference(self, user_id: str, reference_type: str, reference_id: str) -> Optional[CreditTransaction]: ...
    @abstractmethod
    def list_transactions(self, user_id: str, limit: int = 50, offset: int = 0) -> List[CreditTransaction]: ...
    @abstractmethod
    def record_usage(self, usage: CreditUsage) -> CreditUsage: ...
    @abstractmethod
    def get_usage_by_reference(self, user_id: str, reference_type: str, reference_id: str) -> Optional[CreditUsage]: ...
    @abstractmethod
    def list_usage(self, user_id: str, limit: int = 50, offset: int = 0) -> List[CreditUsage]: ...

class ProductRepository(ABC):
    @abstractmethod
    def get_by_id(self, product_id: str) -> Optional[Product]: ...
    @abstractmethod
    def list(self, category: Optional[str] = None, platform: Optional[str] = None, search: Optional[str] = None, sort_by: Optional[str] = None) -> List[Product]: ...
    @abstractmethod
    def update(self, product: Product) -> Product: ...

class CategoryRepository(ABC):
    @abstractmethod
    def list(self) -> List[Category]: ...
    @abstractmethod
    def get_by_id(self, category_id: str) -> Optional[Category]: ...

class PlatformRepository(ABC):
    @abstractmethod
    def list(self) -> List[PlatformMetrics]: ...
    @abstractmethod
    def get_by_slug(self, slug: str) -> Optional[PlatformMetrics]: ...

class WatchlistRepository(ABC):
    @abstractmethod
    def list_product_ids(self, user_id: str) -> List[str]: ...
    @abstractmethod
    def add(self, user_id: str, product_id: str) -> bool: ...
    @abstractmethod
    def remove(self, user_id: str, product_id: str) -> bool: ...
    @abstractmethod
    def is_in_watchlist(self, user_id: str, product_id: str) -> bool: ...

class AlertRepository(ABC):
    @abstractmethod
    def list(self, severity: Optional[str] = None, unread_only: bool = False) -> List[Alert]: ...
    @abstractmethod
    def get_by_id(self, alert_id: str) -> Optional[Alert]: ...
    @abstractmethod
    def create(self, alert: Alert) -> Alert: ...
    @abstractmethod
    def mark_read(self, alert_id: str) -> Optional[Alert]: ...
    @abstractmethod
    def resolve(self, alert_id: str) -> Optional[Alert]: ...

class NotificationRepository(ABC):
    @abstractmethod
    def list(self, unread_only: bool = False) -> List[Notification]: ...
    @abstractmethod
    def mark_read(self, notification_id: str) -> Optional[Notification]: ...
    @abstractmethod
    def mark_all_read(self) -> int: ...

class ReportRepository(ABC):
    @abstractmethod
    def list(self) -> List[Report]: ...
    @abstractmethod
    def get_by_id(self, report_id: str) -> Optional[Report]: ...
    @abstractmethod
    def create(self, report: Report) -> Report: ...
    @abstractmethod
    def update(self, report: Report) -> Report: ...

class DataSourceRepository(ABC):
    @abstractmethod
    def list(self) -> List[DataSource]: ...
    @abstractmethod
    def get_by_slug(self, slug: str) -> Optional[DataSource]: ...
    @abstractmethod
    def update_status(self, slug: str, status: str) -> Optional[DataSource]: ...
    @abstractmethod
    def update(self, data_source: DataSource) -> DataSource: ...

class SettingsRepository(ABC):
    @abstractmethod
    def get_by_user_id(self, user_id: str) -> Optional[UserSettings]: ...
    @abstractmethod
    def update(self, settings: UserSettings) -> UserSettings: ...
