from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status, Query

from backend.app.models.domain import User, LLMUsageRecord
from backend.app.api.deps import get_current_user, get_llm_service, get_llm_usage_repository
from backend.app.services.llm.service import LLMService
from backend.app.repositories.base import LLMUsageRepository
from backend.app.services.llm.provider import (
    LLMAuthError, LLMRateLimitError, LLMTimeoutError, LLMInvalidResponseError, LLMException
)
from backend.app.schemas.llm import (
    AIProductAnalysisRequest, AIProductAnalysisResponse,
    AIProductSummaryRequest, AIProductSummaryResponse,
    AICategoryAnalysisRequest, AICategoryAnalysisResponse,
    AIMarketComparisonRequest, AIMarketComparisonResponse,
    AITrendAnalysisRequest, AITrendAnalysisResponse,
    LLMUsageSummaryResponse
)

router = APIRouter()

def _handle_llm_exception(e: Exception):
    if isinstance(e, KeyError):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=str(e))
    elif isinstance(e, LLMAuthError):
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="LLM provider authentication failed. Please verify system LLM configuration."
        )
    elif isinstance(e, LLMRateLimitError):
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail="Upstream LLM rate limit exceeded. Please try again shortly."
        )
    elif isinstance(e, LLMTimeoutError):
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="LLM analysis request timed out. Please retry."
        )
    elif isinstance(e, LLMInvalidResponseError):
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Invalid structured output generated by LLM."
        )
    elif isinstance(e, LLMException):
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"LLM generation error: {e.message}"
        )
    raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=str(e))


@router.post("/product-analysis", response_model=AIProductAnalysisResponse)
def analyze_product(
    payload: AIProductAnalysisRequest,
    current_user: User = Depends(get_current_user),
    service: LLMService = Depends(get_llm_service)
):
    """
    Executes deep AI Product Analysis using strictly grounded Unified Product Intelligence data.
    """
    try:
        return service.analyze_product(
            unified_product_id=payload.unified_product_id,
            user_id=current_user.id,
            workspace_id=getattr(current_user, "workspace_id", None) or "ws_default",
            force_refresh=payload.force_refresh
        )
    except Exception as e:
        _handle_llm_exception(e)


@router.post("/product-summary", response_model=AIProductSummaryResponse)
def summarize_product(
    payload: AIProductSummaryRequest,
    current_user: User = Depends(get_current_user),
    service: LLMService = Depends(get_llm_service)
):
    """
    Generates a concise executive product summary and positioning brief.
    """
    try:
        return service.summarize_product(
            unified_product_id=payload.unified_product_id,
            user_id=current_user.id,
            workspace_id=getattr(current_user, "workspace_id", None) or "ws_default",
            force_refresh=payload.force_refresh
        )
    except Exception as e:
        _handle_llm_exception(e)


@router.post("/category-analysis", response_model=AICategoryAnalysisResponse)
def analyze_category(
    payload: AICategoryAnalysisRequest,
    current_user: User = Depends(get_current_user),
    service: LLMService = Depends(get_llm_service)
):
    """
    Performs market sector intelligence analysis across category products.
    """
    try:
        return service.analyze_category(
            category=payload.category,
            user_id=current_user.id,
            workspace_id=getattr(current_user, "workspace_id", None) or "ws_default",
            force_refresh=payload.force_refresh
        )
    except Exception as e:
        _handle_llm_exception(e)


@router.post("/market-comparison", response_model=AIMarketComparisonResponse)
def compare_market(
    payload: AIMarketComparisonRequest,
    current_user: User = Depends(get_current_user),
    service: LLMService = Depends(get_llm_service)
):
    """
    Compares multi-platform marketplace listings, price variances, and fulfillment landscape.
    """
    try:
        return service.compare_market(
            unified_product_id=payload.unified_product_id,
            user_id=current_user.id,
            workspace_id=getattr(current_user, "workspace_id", None) or "ws_default",
            force_refresh=payload.force_refresh
        )
    except Exception as e:
        _handle_llm_exception(e)


@router.post("/trend-analysis", response_model=AITrendAnalysisResponse)
def analyze_trend(
    payload: AITrendAnalysisRequest,
    current_user: User = Depends(get_current_user),
    service: LLMService = Depends(get_llm_service)
):
    """
    Evaluates price velocity, volatility, and predictive trajectory from historical snapshots.
    """
    try:
        return service.analyze_trend(
            unified_product_id=payload.unified_product_id,
            user_id=current_user.id,
            workspace_id=getattr(current_user, "workspace_id", None) or "ws_default",
            force_refresh=payload.force_refresh
        )
    except Exception as e:
        _handle_llm_exception(e)


@router.get("/usage", response_model=List[LLMUsageRecord])
def list_llm_usage(
    provider: Optional[str] = Query(None),
    request_type: Optional[str] = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    current_user: User = Depends(get_current_user),
    usage_repo: LLMUsageRepository = Depends(get_llm_usage_repository)
):
    """
    Retrieves telemetry usage records for the current user/workspace.
    """
    return usage_repo.list_usage(
        user_id=current_user.id,
        workspace_id=getattr(current_user, "workspace_id", None) or "ws_default",
        provider=provider,
        request_type=request_type,
        limit=limit,
        offset=offset
    )


@router.get("/usage/summary", response_model=LLMUsageSummaryResponse)
def get_llm_usage_summary(
    current_user: User = Depends(get_current_user),
    usage_repo: LLMUsageRepository = Depends(get_llm_usage_repository)
):
    """
    Returns aggregated token consumption and estimated cost summaries.
    """
    summary = usage_repo.get_summary(
        user_id=current_user.id,
        workspace_id=getattr(current_user, "workspace_id", None) or "ws_default"
    )
    return LLMUsageSummaryResponse(**summary)
